use_frameworks!

platform :ios, '12.0'

target 'DDNetwork_Example' do
  pod 'DDNetwork', :path => '../'

  target 'DDNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
